openapi: 3.0.3
info:
  title: Semantic Kernel API
  version: 0.1.0
paths:
  /api/brief/ideas:
    post:
      summary: Generate ideas from brief
      requestBody:
        required: true
        content:
          application/json:
            schema:
              : '#/components/schemas/BriefInput'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                : '#/components/schemas/IdeaResponse'
components:
  schemas:
    BriefInput:
      type: object
      required: [domain, target, strength]
      properties:
        domain: { type: string }
        target: { type: string }
        strength: { type: string }
        hint: { type: string, nullable: true }
    IdeaCandidate:
      type: object
      properties:
        id: { type: string }
        title: { type: string }
        pitch: { type: string }
    IdeaResponse:
      type: object
      properties:
        briefHash: { type: string }
        ideas:
          type: array
          items:
            : '#/components/schemas/IdeaCandidate'
